### ISSUE TITLE
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

### ISSUE THREAD

**Issue by hiowenluke** [silveroxides/ComfyUI_bnb_nf4_fp4_Loaders#3]
```
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders\__init__.py", line 6, in <module>
    import bitsandbytes as bnb
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\bitsandbytes\__init__.py", line 15, in <module>
    from .nn import modules
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\bitsandbytes\nn\__init__.py", line 21, in <module>
    from .triton_based_modules import (
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 6, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 12, in <module>
    import triton
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\__init__.py", line 13, in <module>
    from . import language
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\language\__init__.py", line 2, in <module>
    from . import core, extern, libdevice, random
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\language\core.py", line 1141, in <module>
    def abs(x):
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 386, in jit
    return JITFunction(args[0], **kwargs)
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
    self.run = self._make_launcher()
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
    scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
  File "D:\ComfyUI\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 82, in version_key
    with open(triton._C.libtriton.__file__, "rb") as f:
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)
```

os: windows 10
cuda: 118
torch: 2.2.0
triton: 2.0.0

**Comment by hiowenluke** [comment]
upgrade triton to 21.0, then it fixed:
```
pip install https://huggingface.co/madbuda/triton-windows-builds/resolve/main/triton-2.1.0-cp310-cp310-win_amd64.whl
```

**Comment by SeBL4RD** [comment]
I just had this problem too.



python_embeded\python.exe -m pip install https://huggingface.co/madbuda/triton-windows-builds/resolve/main/triton-3.0.0-cp312-cp312-win_amd64.whl

python_embeded\python.exe -m pip install https://github.com/kingbri1/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu124torch2.6.0cxx11abiFALSE-cp312-cp312-win_amd64.whl


Fixed.
